name: klit
description: "E926 API client"
publish_to: 'none'
version: 8.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  provider: ^6.1.5+1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.5.4
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  connectivity_plus: ^7.0.0
  pull_to_refresh: ^2.0.0
  uuid: ^3.0.5
  video_player: ^2.10.1
  chewie: ^1.13.0
  fastforge: ^0.6.6
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  confetti: ^0.8.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  linux: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
