display_name: Klit
icon: assets/icon.png
keywords:
  - klit
  - e926
  - gallery
  - image
generic_name: Image Gallery
categories:
  - Graphics
  - Network
startup_notify: true
summary: Image Gallery
vendor: Klit Developer
packager: Klit Developer
packagerEmail: dev@klit.app
license: MIT
url: https://klit.app
