display_name: Klit
icon: assets/icon.png
keywords:
  - klit
  - e621
  - gallery
  - image
generic_name: Image Gallery
categories:
  - Graphics
  - Network
startup_notify: true
summary: E621 compatible image gallery app
group: Application/Graphics
vendor: Klit Developer
packager: Klit Developer
packagerEmail: dev@klit.app
license: MIT
url: https://github.com/klit/klit
