import 'package:kilt/post/post.dart';
import 'package:kilt/shared/shared.dart';

Post makePost({
  int id = 1,
  String? file = 'https://example.com/image.jpg',
  String? sample,
  String? preview,
  int width = 1000,
  int height = 800,
  String ext = 'jpg',
  int size = 500000,
  Map<String, String?>? variants,
  Map<String, List<String>> tags = const {
    'general': ['fox', 'canine'],
    'species': ['dog'],
  },
  int uploaderId = 100,
  String? uploaderName = 'uploader',
  DateTime? createdAt,
  DateTime? updatedAt,
  int? changeSeq,
  int? approverId,
  VoteInfo? vote,
  bool isDeleted = false,
  Rating rating = Rating.s,
  int favCount = 10,
  bool isFavorited = false,
  int commentCount = 5,
  String description = 'A test post',
  List<String> sources = const ['https://example.com/source'],
  List<int>? pools,
  List<String>? lockedTags,
  Relationships? relationships,
}) {
  return Post(
    id: id,
    file: file,
    sample: sample,
    preview: preview,
    width: width,
    height: height,
    ext: ext,
    size: size,
    variants: variants,
    tags: tags,
    uploaderId: uploaderId,
    uploaderName: uploaderName,
    createdAt: createdAt ?? DateTime(2024, 1, 15),
    updatedAt: updatedAt,
    changeSeq: changeSeq,
    approverId: approverId,
    vote: vote ?? const VoteInfo(score: 50),
    isDeleted: isDeleted,
    rating: rating,
    favCount: favCount,
    isFavorited: isFavorited,
    commentCount: commentCount,
    description: description,
    sources: sources,
    pools: pools,
    lockedTags: lockedTags,
    relationships: relationships ?? const Relationships(parentId: null, hasChildren: false, hasActiveChildren: false, children: []),
  );
}
